version: '3.5'

services:
  solar:
    build: .
    container_name: solar
    depends_on:
      - mysql
      - mysql-test
    volumes:
      - .:/var/www/html

  mysql:
    container_name: solardb
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel
    volumes:
      - db-data:/var/lib/mysql

  mysql-test:
    container_name: solardb-test
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing
volumes:
  db-data:
